# Generated by Django 5.2 on 2025-04-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/')),
                ('processed_file', models.ImageField(blank=True, null=True, upload_to='processed_images/')),
            ],
            options={
                'indexes': [models.Index(fields=['file'], name='media_app_i_file_3136cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed_videos/')),
            ],
            options={
                'indexes': [models.Index(fields=['file'], name='media_app_v_file_23a14e_idx')],
            },
        ),
    ]
